from __future__ import annotations

import re
from dataclasses import dataclass
from urllib.parse import parse_qs, urlparse


URL_RE = re.compile(r"https?://[^\s]+", re.IGNORECASE)


@dataclass(frozen=True)
class ParsedInput:
    kind: str
    value: str
    platform: str = ""
    player_id: int | None = None


def parse_main_input(raw: str) -> ParsedInput:
    text = raw.strip()
    if not text:
        raise ValueError("请输入雀魂/天凤牌谱链接，或粘贴 mjai-reviewer --json 输出。")

    if text.startswith("{") or text.startswith("["):
        return ParsedInput(kind="json", value=text)
    if "<html" in text[:200].lower() or "generated by" in text.lower() and "mjai-reviewer" in text.lower():
        return ParsedInput(kind="official_result_html", value=text, platform="official")

    url_match = URL_RE.search(text)
    if not url_match:
        raise ValueError("没有识别到 JSON 或牌谱链接。雀魂链接可以直接粘贴完整的“雀魂牌譜: https://...”文本。")

    url = url_match.group(0).rstrip("。).,，")
    parsed = urlparse(url)
    host = (parsed.hostname or "").lower()
    qs = parse_qs(parsed.query)

    if "mjai.ekyu.moe" in host or "mortal.ekyu.moe" in host:
        return ParsedInput(kind="official_result_url", value=url, platform="official")

    if "tenhou.net" in host:
        player_id = _parse_player(qs.get("tw", [""])[0])
        return ParsedInput(kind="tenhou_url", value=url, platform="tenhou", player_id=player_id)

    if "maj-soul.com" in host or "mahjongsoul" in host:
        return ParsedInput(kind="majsoul_url", value=url, platform="majsoul")

    raise ValueError(f"暂不支持这个牌谱链接来源：{host}")


def _parse_player(value: str) -> int | None:
    try:
        player = int(value)
    except ValueError:
        return None
    return player if 0 <= player <= 3 else None
