from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Callable

from link_utils import parse_main_input


OFFICIAL_URL = "https://mjai.ekyu.moe/zh-cn.html"


@dataclass(frozen=True)
class OfficialReviewResult:
    source_url: str
    result_url: str
    html: str
    rating_percent: float | None


def run_official_review(
    raw_input: str,
    *,
    model_tag: str = "4.1b",
    ui_mode: str = "killerducky",
    progress: Callable[[str], None] | None = None,
) -> OfficialReviewResult:
    try:
        from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise RuntimeError(
            "Playwright is not installed. Run: python -m pip install playwright && python -m playwright install chromium"
        ) from exc

    parsed = parse_main_input(raw_input)
    if parsed.kind not in {"majsoul_url", "tenhou_url"}:
        raise ValueError("Please paste a Mahjong Soul or Tenhou paipu URL for official Mortal automation.")

    source_url = parsed.value

    def emit(message: str) -> None:
        if progress:
            progress(message)

    with sync_playwright() as p:
        emit("Opening official Mortal page...")
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        try:
            page.goto(OFFICIAL_URL, wait_until="domcontentloaded", timeout=60_000)
            page.wait_for_selector("form[name=reviewForm]", timeout=60_000)

            emit("Filling official Mortal review form...")
            page.fill("input[name=log-url]", source_url)
            page.select_option("select[name=engine]", "mortal")
            page.select_option("select[name=mortal-model-tag]", model_tag)
            page.select_option("select[name=ui]", ui_mode or "killerducky")
            page.select_option("select[name=lang]", "zh-CN")
            page.eval_on_selector("input[name=show-rating]", "el => el.checked = true")

            emit("Waiting for official verification to enable Submit. If a verification box appears, complete it in the opened window.")
            try:
                page.wait_for_function(
                    """
                    () => {
                      const btn = document.querySelector('form[name=reviewForm] button[type=submit]');
                      return btn && !btn.disabled;
                    }
                    """,
                    timeout=300_000,
                )
            except PlaywrightTimeoutError as exc:
                raise RuntimeError(
                    "Official Mortal did not enable Submit within 5 minutes. Please retry; if a verification box appears, complete it in the opened browser window."
                ) from exc

            emit("Submitting to official Mortal. Waiting for analysis result...")
            page.click("form[name=reviewForm] button[type=submit]")

            try:
                page.wait_for_function(
                    """
                    () => {
                      const text = document.body ? document.body.innerText : '';
                      return text.includes('Generated by') && text.includes('mjai-reviewer');
                    }
                    """,
                    timeout=900_000,
                )
            except PlaywrightTimeoutError as exc:
                body = page.locator("body").inner_text(timeout=10_000)
                raise RuntimeError(f"Official Mortal did not finish within 15 minutes. Current page says: {body[:500]}") from exc

            emit("Result received. Saving local copy...")
            html = page.content()
            text = page.locator("body").inner_text(timeout=10_000)
            rating_percent = extract_rating_percent(text)
            return OfficialReviewResult(
                source_url=source_url,
                result_url=page.url,
                html=html,
                rating_percent=rating_percent,
            )
        finally:
            browser.close()


def extract_rating_percent(text: str) -> float | None:
    patterns = [
        r"(?im)^rating\s*\n\s*([0-9]+(?:\.[0-9]+)?)\s*$",
        r"(?i)\brating\b[^0-9]{0,30}([0-9]+(?:\.[0-9]+)?)",
    ]
    for pattern in patterns:
        match = re.search(pattern, text)
        if not match:
            continue
        try:
            value = float(match.group(1))
        except ValueError:
            continue
        if 0 <= value <= 100:
            return value
    return None
